Fixes #3: OpenMP build error on vc14
This ensures OpenMP 2.5 compatibility instead of 3+ and fixes:

Error C3016	'i': index variable in OpenMP 'for' statement must have signed integral type